export const GET_RESTAURANT = 'GET_RESTAURANT'
export const SET_LOADING = "SET_LOADING"
export const RESTAURANT_RES = 'RESTAURANT_RES'
export const GET_LOCATION = 'GET_LOCATION'
export const LOCATION_RES= 'LOCATION_RES'